LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_CFLAGS += -D_XOPEN_SOURCE -D_GNU_SOURCE -DANDROID_GADGET=0 -DANDROID_SMP=0 -D_POSIX_VDISABLE=0
LOCAL_CFLAGS += -DHAVE_FORKEXEC -DHAVE_TERMIO_H
LOCAL_CFLAGS += -I.
LOCAL_LDLIBS+= -L$(SYSROOT)/usr/lib -llog

LOCAL_MODULE    := first
LOCAL_SRC_FILES := first.cpp

include $(BUILD_SHARED_LIBRARY)
